# -*- mode: ruby -*-
# vi: set ft=ruby :
MANAGE_HOST = true
MANAGE_GUEST = true
PRIVATE_NET_PREFIX='10.0.0'
MEMORY="2048"

if Gem::Version.new(::Vagrant::VERSION) < Gem::Version.new('1.5')
  Vagrant.require_plugin('vagrant-hostmanager')
end

Vagrant.configure('2') do |config|

  if ENV.key? 'VAGRANT_BOX'
    config.vm.box = ENV['VAGRANT_BOX']
  else
    config.vm.box = 'centos/7'
  end

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define :master do |server|
    server.vm.hostname = 'master'
    server.vm.network :private_network, :ip => "#{PRIVATE_NET_PREFIX}.2"
    server.hostmanager.aliases = %w(master)
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
    end
  end

  config.vm.define :slave do |server|
    server.vm.hostname = 'slave'
    server.vm.network :private_network, :ip => "#{PRIVATE_NET_PREFIX}.3"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
    end
  end
end
